run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive

linters-settings:
  revive:
    rules:
      - name: var-naming
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
